version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=your-very-secure-secret-key-1234567890
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/password_manager
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3307:3306" # змінив зовнішній порт
    environment:
      - MYSQL_DATABASE=password_manager
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
